services:
  db:
    image: postgres:16
    container_name: url-shortener-db
    environment:
      POSTGRES_USER: shortener
      POSTGRES_PASSWORD: shortener
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - url-shortener-db-data:/var/lib/postgresql/data

volumes:
  url-shortener-db-data:
